FROM node:24.12.0-slim

ARG USER_ID=1000

RUN apt update && \
    apt install -y curl gpg gnupg gpg-agent socat sqlite3 build-essential python3

RUN usermod -u ${USER_ID} node

USER node

WORKDIR /home/node/app

EXPOSE 3000 
